name: accumuloadapter
channels:
  - gbrener
  - defaults
  - conda-forge
dependencies:
  - python
  - ipython
  - numpy
  - pandas
  - pytest
  - cython
  - openssl
  - thrift =0.10.0
  - boost
  - pytest-cov
  - pytest-xdist
